version: '3.2'
services:

  es:
    container_name: es
    hostname: es
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    environment:
      - "ES_JAVA_OPTS=-Xms500m -Xmx500m -Des.allow_insecure_settings=true"
      - xpack.security.enabled=false
      - bootstrap.system_call_filter=false
      - bootstrap.memory_lock=true
      - http.host=0.0.0.0
      - transport.host=localhost
      - cluster.name=itest
      - discovery.type=single-node
    networks:
      - stack
    ulimits:
      nproc: 65535
      nofile: 65535
      memlock: -1
    ports:
      - 9200:9200
    user: elasticsearch
    command: >
      /bin/sh -c "./bin/elasticsearch-plugin install --batch http://es-learn-to-rank.labs.o19s.com/ltr-${LTR_PLUGIN_VERSION}-es${ELASTICSEARCH_VERSION}.zip;
      /usr/local/bin/docker-entrypoint.sh"
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health"]

  search-api:
    container_name: search-api
    build:
      context: ../../../../
      args:
        ARTIFACT: ./build/libs/search-api.jar
    networks:
      - stack
    image: search-api:itest-latest
    depends_on:
      - es
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - ES_HOSTNAME=es
      - "JAVA_OPTS=-Xmx500m -Xms500m"
    ports:
      - 8482:8482

networks: {stack: {}}
